name          'puppet-erlang'
version       '0.1.0'
source        'UNKNOWN'
author        'imperialwicket'
license       'Apache License, Version 2.0'
summary       'Erlang installation from source.'
description   'Install Erlang from source at a configurable version'
project_page  'https://github.com/imperialwicket/puppet-erlang'

dependency 'puppetlabs/stdlib'
